Fix handling of unicode arguments on windows
xamarin/xamarin-android-binutils pull request #5
Opened 2023-09-18 14:29 UTC by BrzVlad

This commit tweaks the `as.exe` tool to handle passing of file paths containing non ascii characters. This is done in the following steps:
- on windows, we don't use the `argc` and `argv` from main, since they only support ascii (unlike on linux where they contain utf8 directly). We use instead the windows api `CommandLineToArgvW` to get the arguments in utf16 and then convert it to utf8.
- when parsing the arguments and creating `std::filesystem::path`, we cast the `optarg` char* to the C++20 type char8_t* so the path constructor knows the string is in utf8 encoding.
- when creating the process, we convert the args from u8 to utf16 and use the wide char version of `CreateProcess`

This commit coupled with some mono aot fixes enables the compilation of a maui sample with special characters in project name. (https://github.com/dotnet/runtime/issues/83203)

2023-09-18 14:52 UTC, grendello requested changes

2023-09-19 14:04 UTC, grendello commented on src/gas/process.windows.cc
> +	delete wargs;
Damn, sorry I missed it the first time. `delete[]` should be used here and in the line below.

2023-09-19 14:08 UTC, BrzVlad commented on src/gas/process.windows.cc
> +	delete wargs;
C++ noob here. Any idea what `delete` is doing in this case then ? What is the point of `delete[]` in C++ ? :D

2023-09-19 14:19 UTC, grendello commented on src/gas/process.windows.cc
> +	delete wargs;
They are different overloads of the operator. `delete` will be translated to `operator delete(void*)` while `delete[]` to `operator delete[](void*)` - the implementation might have different code to handle "simple" vs array pointers.  The rule of the thumb is that if you allocate with `new[]` you delete with `delete[]`

2023-09-19 20:03 UTC, merged